Defense
NonameUntitled/RoutingLibrary pull request #13
Opened 2023-06-23 17:11 UTC by zhog96

2023-06-24 19:08 UTC, NonameUntitled requested changes

2023-06-24 19:08 UTC, NonameUntitled commented on agents/ppo.py
> +    def _trajectory_loss(self, trajectory):
Please add shape descriptions/hints for this function (the same is applied for dqn.py)

2023-06-24 19:08 UTC, NonameUntitled commented on agents/ppo.py
> +        prob_ratio = torch.exp(torch.clamp(next_logprob - next_logprob_old, -300, 300))
Add -300 and 300 in class variables

2023-06-24 19:08 UTC, NonameUntitled commented on configs/base/pretrain_config.json
Let's discuss the structure of config dir later

2023-06-24 19:15 UTC, zhog96 commented on agents/ppo.py
>              end_v_old = 0
If trajectory ended in sink, what else should we use, v-func is needed only if we sampled unfinished trajectory? =)

2023-06-24 19:19 UTC, zhog96 commented on configs/base/pretrain_config.json
I think we should first discuss the way we split and build configs, cause i am going crazy with all this copy-paste =)

2023-06-24 19:21 UTC, zhog96 commented on agents/ppo.py
> +            'predicted_next_node_logits': neighbors_logits,  # [neighbor_node_ids.mask].flatten(),
some issues with mse and cross-entropy losses in pretrain)

2023-07-01 22:13 UTC, NonameUntitled requested changes

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorSimulation.py
> +            else:
I don't like `else` here. Let's write `elif` for clarification

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorSimulation.py
> +                else:
The same story with `else` here

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorSimulation.py
> +        # yield self._world_env.timeout(1000)
Let's write some description for this comment

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorsEnvironment.py
> +                    # values=torch.tensor([sample[key]], dtype=torch.int64),
Let's remove this comment

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorsEnvironment.py
> +        # sample_tensor[dv_agent._bag_ids_prefix] = torch.LongTensor([bag.id])
Let's remove this comment

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorsEnvironment.py
> +        # TODODO: smth here
lol

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorsEnvironment.py
> +        # TODODO: smth here
lol x2

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorsEnvironment.py
> +            f'Collisions/time',
You don't need f-string here

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/ConveyorsEnvironment.py
> +            "Bag lost/time",
Let's use the same parenthesis everywhere (`'` instead of `"`)

2023-07-01 22:13 UTC, NonameUntitled commented on simulation/conveyor/model.py
> +                self._logger.debug("WHATEVER1")
lol x3

2023-07-09 09:48 UTC, zhog96 commented on agents/dqn.py
> +        self._optimizer_factory = optimizer_factory
for copy

2023-07-09 09:51 UTC, zhog96 commented on agents/dqn.py
> +            length=2
code below will work only with constant 2, no sense?

2023-07-09 09:54 UTC, zhog96 commented on agents/dqn.py
>          # TODO[Zhogov Alexandr] fix it
The fact we use hardcoded dict below

2023-07-09 09:56 UTC, zhog96 commented on ml/callbacks.py
> +                    inputs.get(self._loss_prefix, 0.0),
?, this is map<String, Double>

2023-07-09 10:02 UTC, zhog96 commented on ml/utils.py
> +        if self._padded_values_cache is not None:
Let's discuss it. Inplace operations may be fatal, but we got errors using them in backward later?

2023-07-09 10:07 UTC, zhog96 commented on topology/base.py
> +                graph.add_node(
Cause they are used for connecting conveyor ends below. For example, without this line build of conveyors cycle will crash.

2023-07-10 23:05 UTC, NonameUntitled commented on agents/dqn.py
> +            length=2
I see comment, LTGM

2023-07-10 23:07 UTC, NonameUntitled commented on agents/ppo.py
> +            'predicted_next_node_logits': neighbors_logits,  # [neighbor_node_ids.mask].flatten(),
Can you provide more context?

2023-07-10 23:11 UTC, NonameUntitled commented on ml/callbacks.py
> +                    inputs.get(self._loss_prefix, 0.0),
My bad, sorry

2023-07-10 23:15 UTC, NonameUntitled approved these changes

2023-07-18 20:46 UTC, zhog96 commented on environments/conveyor.py
> +           _THETA_3 * T * T / V + (_THETA_4_L * length / 3.6 + _k_2) * T + V * V * T / 3.6
let it be in git history, will think about right formulas later

2023-07-22 13:27 UTC, merged